# Generated by Django 2.2.4 on 2019-08-29 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ong',
            name='horario_atendimento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ong',
            name='nome_responsavel',
            field=models.CharField(max_length=50, verbose_name='Responsavel pela Ong'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='observacoes',
            field=models.TextField(),
        ),
    ]
